
export const title = 'CONTRATO DE LICENCIAMIENTO Y PRESTACIÓN DE SERVICIOS TECNOLÓGICOS PARA LA PLATAFORMA KUPI (TIPO CLOUD COMPUTING)';

export const tableContract = (client, nitClient, noContrato) => {
  return [
    {label: 'CONTRATO no.', value: noContrato, blond: true},
    {label: 'CLIENTE CONTRATANTE', value: client, blond: true},
    {label: 'NIT', value: nitClient, blond: false},
    {label: 'CONTRATISTA', value: 'KUPI', blond: true},
    {label: 'NIT', value: '901.165.868-2', blond: false},
    {label: 'LICENCIA', value: 'Plataforma Kupi', blond: false},
    {label: 'DURACIÓN', value: '1 año Renovable', blond: false},
  ]
};

export const contractSections = () => {
  return [
    {
      title: 'I. PARTES',
      pagraphs: [
        'i. KUPI GROUP S.A.S., sociedad comercial, identificada con NIT: 901.165.868-2, domiciliada en Tuluá – Valle, representada legalmente por el señor ALVARO GOMEZ SANCLEMENTE, mayor de edad, identificado con cédula de ciudadanía No. 94.365.201 expedida en Tuluá, según consta en certificado de existencia y representación adjunto, con capacidad para actuar y obligar a la compañía, en adelante KUPI.',
        'ii. EL CLIENTE, identificado como firma en el presente contrato, individualizado conforme a documento anexo de identificación adjunto al presente contrato, con capacidad para actuar y obligarse, en adelante y para todos los efectos contractuales, EL CLIENTE.',
        'Las personas arriba identificadas, conforman “las partes”, y de forma individual “la parte” Las Partes hemos acordado suscribir el presente Contrato en los términos y condiciones que se establecen a continuación, previas las siguientes:'
      ]
    },
    {
      title: 'CONSIDERACIONES',
      pagraphs: [
        'i. KUPI, es una empresa de la industria TI, prestadora de servicios tecnológicos, y creadora de la Plataforma tecnológica denominada KUPI, en adelante la plataforma, con la cual presta un servicio en línea (web), de interconexión o integración entre empresas que desean otorgar cupos de dinero a sus colaboradores, trabajadores, contratistas, o personas que ellos determinen, para que obtengan productos y/o servicios; y los comercios que prestan dichos servicios o venden dichos productos. La plataforma KUPI opera como integradora entre usuarios que compran, comercios que venden (EL CLIENTE) y empresas que han asignado un cupo a sus colaboradores.',
        'ii. La plataforma tecnológica asigna un acceso o licencia a EL CLIENTE, para que pueda realizar ventas en su establecimiento de comercio a los usuarios de KUPI.',
        'iii. EL CLIENTE, es una persona jurídica o natural que ofrece bienes y/o servicios, y desea beneficiarse de los usuarios KUPI quienes a través de la plataforma pueden adquirir los bienes y/o servicios ofrecidos.'
      ]
    },
    {
      title: 'DEFINICIONES',
      pagraphs: [
        'Comerciantes: Personas naturales o jurídicas que ofrecen bienes y servicios de diversa índole.',
        'Usuarios: Usuarios de la aplicación KUPI, quienes tienen los saldos disponibles, para acceder a los bienes y/o servicios ofrecidos por los comerciantes.',
      ]
    },
    {
      title: 'CLÁUSULAS',
      pagraphs: [
        'PRIMERA: OBJETO: Mediante el presente contrato KUPI, entrega una licencia de uso temporal a favor del CLIENTE de la plataforma “KUPI”, para realizar ventas en la modalidad de servicio software como servicio “SaaS” o Cloud Computing, a cambio de un precio pagadero por EL CLIENTE.',
        '',
        'SEGUNDA: USO DE LA PLATAFORMA: El uso de la plataforma KUPI, será el determinado en el manual de administrador comercio y manual cajeros, que forman parte integral del presente contrato y son aceptados por el cliente al momento de iniciar el uso de la plataforma.',
        '',
        'TERCERA: OBLIGACIONES DEL CLIENTE:',
        '• Prestar toda la colaboración que requiera KUPI para la ejecución de este contrato, como es el caso de diligenciar toda la documentación solicitada con datos veraces y reales para el uso de la plataforma, recibir la capacitación para la utilización de esta y capacitar a su personal acerca de KUPI.',
        '• Pagar a KUPI el precio pactado, por el uso de la plataforma.',
        '• Respetar el precio inicialmente ofrecido al consumidor como valor final de la compra, sin incrementarlo por la utilización de la plataforma.',
        '• Respetar las normas de propiedad intelectual y derechos de autor, entendiendo que el software utilizado es de propiedad exclusiva de KUPI GROUP S.A.S., la licencia otorgada no acarrea transferencia de los derechos morales ni patrimoniales y de ningún otro distinto al uso de la plataforma para el desarrollo del objeto del presente contrato.',
        '• No utilizar el Sistema para facilitar, ocultar, manejar, invertir o aprovechar de cualquier forma dineros o bienes provenientes de actividades ilícitas, o para dar apariencia de legalidad a actividades ilícitas y a recursos vinculados con las mismas.',
        '• Mantener actualizada su dirección física, teléfono, dirección de correo electrónico, cuenta bancaria e información financiera que requiera KUPI.',
        '• No permitir que terceros utilicen o se beneficien de la Plataforma KUPI.',
        '• Suministrar a los usuarios de KUPI y consumidores en general, información cierta, fidedigna, suficiente, clara y actualizada respecto de los precios de los productos y servicios, calidad de estos, condiciones contractuales y en general dar cumplimiento de las normas consagradas en el estatuto del consumidor.',
        '• Acatar los reglamentos y recomendaciones que KUPI expida para que su sistema funcione de manera óptima y segura.',
        '• Tomar las medidas de seguridad necesarias y abstenerse de facilitar que virus, gusanos u otras rutinas de programación interfieran o dañen el sistema de KUPI.',
        '• Atender las recomendaciones de KUPI y de los consumidores, respecto de quejas, peticiones y sugerencias de mejora en la prestación de su servicio, y en la utilización de la plataforma KUPI.',
        '• Tomar las medidas de seguridad y buenas prácticas para el funcionamiento de la plataforma y abstenerse de adoptar prácticas que impongan una carga desproporcionada a la infraestructura tecnológica de KUPI.',
        '• Mantener sus propias conexiones a Internet, ancho de banda que permitan la navegación en la plataforma y las ventas a través de ella, verificando que sea posible navegar, cerrando sesiones o dispositivos colgados o conectados a su propia red que impida el uso del Internet, pausando si es el caso, la reproducción de videos o descargas que consuman el ancho de banda o los datos, entre otras.',
        '• Pagar la cláusula penal en caso de incumplimiento contractual.',
        '• Prestar la disposición y facilitar la capacitación del personal encargado de recibir las transacciones KUPI, facilitando el uso de la plataforma al consumidor y garantizando la calidad en la prestación del servicio.',
        '• Prestar colaboración para el desarrollo de estrategias comerciales y de mercadeo que permitan incentivar el uso de la plataforma en el comercio.',
        '• Guardar absoluta reserva sobre la información técnica, financiera, operativa o comercial a que llegare a tener acceso, absteniéndose de emplearla para el desarrollo de actividades diferentes de las que constituyen el objeto de este CONTRATO.',
        '',
        'CUARTA: OBLIGACIONES DE KUPI',
        '• Cumplir con el objeto, naturaleza y fines del contrato.',
        '• Mantener los esfuerzos comerciales para el posicionamiento de mercado de la aplicación KUPI, velando por el aumento de consumidores para EL CLIENTE; teniendo en cuenta que esta obligación es de medio y no de resultado.',
        '• KUPI hará esfuerzos razonables para mantener la funcionalidad de los aplicativos o herramientas que utilice o le suministre al CLIENTE, para mitigar los riesgos a los que esté expuesta la tecnología, tales como, la interceptación no autorizada de terceros, fugas de información, funcionalidad de la plataforma, entre otros.',
        '• Brindar soporte técnico y capacitación, al CLIENTE en lo relacionado con la plataforma, así como brindar el soporte necesario para el uso de esta.',
        '• Entregar al CLIENTE los pagos de las ventas efectivamente realizadas a través de la plataforma KUPI, en los términos pactados en el presente contrato.',
        '• Facturar el precio del contrato al CLIENTE.',
        '',
        'QUINTA: PRECIO Y FORMA DE PAGO',
        'EL CLIENTE pagará por concepto de uso de la plataforma el 1% de las ventas realizadas efectivamente, por el primer año de ejecución del presente contrato.',
        'Para el pago, KUPI descontará el precio pactado del valor de las ventas realizadas por EL CLIENTE, conforme a las liquidaciones semanales realizadas; y presentará al CLIENTE la respectiva factura de forma semanal por concepto del servicio prestado.',
        'Parágrafo primero: Las partes se obligan a no divulgar el porcentaje acordado en la presente clausula, esta información se considera confidencial, por tanto, no podrá ser difundida a personas naturales o jurídicas distintas a las que suscriben este contrato.',
        'Parágrafo segundo: Las partes de común acuerdo, ajustarán el precio del presente contrato anualmente, teniendo en cuenta el rendimiento y ventas realizadas por el uso de la plataforma.',
        'Parágrafo tercero: Los comercios asumirán los costos derivados del uso de la plataforma según el consumo de los usuarios del FONDEADOR, de acuerdo con los descuentos reconocidos a KUPI.',
        '',
        'SEXTA: VIGENCIA',
        'El término del presente contrato será de un (1) año, contados a partir de la fecha de firma de este.',
        'El contrato se prorrogará de forma automática, por un tiempo igual al inicialmente pactado, si ninguna de las partes manifiesta a la otra con un plazo no menor de noventa (90) días calendario, su intención de darlo por terminado. Durante las prórrogas también aplicará la penalidad por terminación anticipada. En caso de terminación anticipada cualquier saldo a favor del CLIENTE o de KUPI deberá ser cancelado para liquidar el contrato.',
        '',
        'SÉPTIMA: INCUMPLIMIENTOS CONTRACTUALES',
        'Serán incumplimientos contractuales, que darán lugar al cobro de la cláusula penal y demás acciones pertinentes, cualquier incumplimiento de lo pactado en este contrato y los siguientes:',
        '• Cuando EL CLIENTE no se disponga a recibir la capacitación para el buen uso de la plataforma, le traslade el costo de la utilización a los usuarios, no reciba o manifieste no recibir el medio de pago sin justificación y genere quejas reiterativas por el servicio prestado o genere perjuicio a KUPI de su imagen comercial.',
        '• Cuando el cliente permita que terceros utilicen o se beneficien de la Plataforma KUPI.',
        '• Utilizar el Sistema para facilitar, ocultar, manejar, invertir o aprovechar de cualquier forma dineros o bienes provenientes de actividades ilícitas, o para dar apariencia de legalidad a actividades ilícitas y a recursos vinculados con las mismas.',
        '• No suministrar a los usuarios de KUPI y consumidores en general, información cierta, fidedigna, suficiente, clara y actualizada respecto de los precios de los productos y servicios, calidad de estos, condiciones contractuales y en general incumplir las normas consagradas en el estatuto del consumidor.',
        '• Trasladar el valor del uso de la plataforma a los usuarios o consumidores de la plataforma. EL CLIENTE debe facturar sus ventas por el precio publicitado, no podrá aumentar el precio de sus productos o servicios por el uso del medio de pago KUPI.',
        '• Cuando EL CLIENTE termine unilateralmente el contrato, sin justa causa.',
        '• Cuando EL CLIENTE no acate las recomendaciones sobre la implementación adecuada de la plataforma, seguridad y óptimo funcionamiento del sistema KUPI o por su incursión en actividades de hacking o violación de seguridad de los sistemas de KUPI GROUP.',
        '• La realización de actos en contra de los usuarios de la plataforma como no recibir el medio de pago de forma injustificada, cobrar porcentajes adicionales para recibir KUPI, atentar contra la imagen de KUPI, entre otros que afecten la imagen y reputación de KUPI.',
        '• Divulgar información que se conozca de KUPI en desarrollo del presente contrato o de las condiciones contractuales aquí acordadas.',
        '',
        'OCTAVA: AUTORIZACIONES Y DECLARACIONES',
        'Con la firma del presente contrato LAS PARTES declaran y aceptan que:',
        '• El Servicio KUPI GROUP S.A.S. No es un servicio bancario, y no capta dinero de ninguna persona natural o jurídica, es un servicio de integración que permite unir comercios, compradores y empresas que otorgan cupos a sus colaboradores o afiliados. Facilita a las empresas la eliminación de adelantos de nómina, préstamos en efectivo, entrega de bonos, y otras condiciones propias de las relaciones entre empleadores y trabajadores o contratistas. Y por parte de los comercios les permite acceder a mayor cobertura ya que la plataforma cuenta con usuarios registrados que podrán consumir los productos y servicios de los CLIENTES de KUPI.',
        '• EL CLIENTE será el único responsable del uso, cuidado y custodia de su clave o password, por lo que toda transacción realizada utilizando dichas claves o passwords, se presumirá realizada por éste, quedando liberada, a partir de ese momento a KUPI GROUP de toda responsabilidad respecto de eventuales pérdidas derivadas por el mal uso de su clave.',
        '• EL CLIENTE se responsabiliza legal y económicamente ante cualquier consecuencia que genere el uso indebido o fraudulento del sistema KUPI.',
        '• EL CLIENTE, es la única persona autorizada para utilizar el sistema KUPI esto implica que él no podrá prestar el servicio a terceros, ni servir como puente, facilitador, mandatario, arrendador o cualquier otro esquema comercial o jurídico.',
        '• EL CLIENTE se responsabiliza legal y económicamente ante cualquier riesgo que genere la actividad que realiza, los productos que comercializa, los servicios que presta y en general será el único responsable civil, administrativa, comercial, penalmente, por la afectación a la vida, salud, bienes, patrimonio de los usuarios que consumen sus productos o servicios y en general responsable legalmente de cumplir las normas propias de su actividad y las del estatuto del consumidor, dejando indemne a KUPI GROUP S.A.S., por cualquier responsabilidad de sus actos u omisiones como comerciante, considerando que KUPI no es quien vende, sino que es una plataforma que integra el usuario con el comercio.',
        '• EL CLIENTE autoriza que KUPI realice la consulta, reporte y actualización de las bases de datos como datacrédito, cifin y demás del sistema financiero o bancario que establezca, además de las listas nacionales o internacionales sobre el sistema de prevención de riesgos de lavado de activos y financiación del terrorismo SARLAFT.',
        '• El CLIENTE libera a KUPI GROUP de cualquier responsabilidad en relación con transferencias de dinero erróneas o que no resulten exitosas debido a la información que el CLIENTE haya reportado.',
        '• Las obligaciones de KUPI en la prestación de los servicios es de medios y no de resultado, se obliga a prestar los servicios de manera segura, no garantiza número de ventas, o incrementos de estas, KUPI cumple está obligación con la sola presencia del comercio en su plataforma o APP, en la cual los usuarios pueden consultar los comercios aliados en los que pueden comprar,',
        '• En caso de que exista cualquier reclamación con respecto al servicio prestado o productos vendido por conceptos de garantía, devoluciones será EL CLIENTE o EL COMERCIO quien deberá responder ante el usuario, entendiendo que como tal KUPI es exclusivamente medio de pago.',
        '',
        'NOVENA: VINCULACIÓN',
        'Este contrato es de carácter comercial, LAS PARTES actuarán con independencia legal, jurídica, administrativa y financiera, en ningún caso se entenderá que exista relación laboral alguna entre las partes, sus funcionarios o empleados, los funcionarios, colaboradores y contratistas de KUPI GROUP S.A.S., y los empleados, funcionarios, colaboradores y contratistas de EL CLIENTE que intervengan en el servicio contratado, o en la utilización de la plataforma. No existirá solidaridad, subordinación o dependencia alguna entre éstos y EL CLIENTE o KUPI GROUP S.A.S., cada parte responderá por sus propias cargas y obligaciones fiscales, comerciales, laborales y de toda índole y mantendrá indemne a la otra parte conforme a dichas obligaciones.',
        '',
        'DÉCIMA: EXCLUSIVIDAD',
        'La relación entre KUPI GROUP y el CLIENTE no es exclusiva y podrán tener acuerdos con más comercios de igual, similar o diferente actividad, dentro o fuera del mismo territorio, por tanto, KUPI tendrá otros CLIENTES de igual o similares calidades y el CLIENTE podrá tener otros medios para recibir las ventas de sus CLIENTES.',
        'La licencia otorgada será para USO EXCLUSIVO del CLIENTE en la República de Colombia, de conformidad con los términos del presente contrato y de la legislación colombiana, en especial la reglamentación para servicios de tipo computación en la nube, cloud computing.',
        '',
        'DÉCIMA PRIMERA: EXENCIONES DE RESPONSABILIDAD',
        'LAS PARTES recíprocamente aceptan que no serán responsables civil, comercial, penal ni administrativamente y renuncian a ejercer cualquier acción legal solicitando indemnización de perjuicios, gastos o daños actuales o futuros uno en contra del otro por los siguientes conceptos:',
        '• Retrasos en el procesamiento de transacciones que afecten disponibilidad de los recursos o dineros, por caso fortuito o causas no imputables a las partes.',
        '• Ocurrencia de caso fortuito o fuerza mayor tales como sismos, cortes de energía eléctrica y/o del servicio telefónico y/o de líneas de transmisión de datos, intervenciones de redes por partes de terceros, no funcionamiento de redes públicas y/o privadas, actos terroristas, huelgas o similares, que impidan mantener en funcionamiento u operativo los sistemas necesarios para la operación de este contrato.',
        '• Interceptación y/o uso de datos relacionados entre las partes por terceras personas no autorizadas, incluyendo los efectos y consecuencias de dicho uso.',
        '• Cualquier circunstancia sobre la cual las partes no tengan control directo, incluyendo problemas de equipos de computación, equipos de comunicaciones, software (incluyendo virus) o proveedores de Internet, entre otros.',
        '• Interrupción transitoria del sistema informático de las partes.',
        '• Cualquier impedimento del uso o acceso a los sistemas o sitios WEB de las partes por cualquier motivo o causa no imputable a ellas.',
        '',
        'DÉCIMA SEGUNDA: CAUSALES DE TERMINACIÓN',
        'El presente contrato se terminará en los siguientes casos:',
        '1. Por incumplimiento de las obligaciones contenidas en el presente contrato.',
        '2. Por común acuerdo de LAS PARTES.',
        '3. Por vencimiento del término del contrato, sin que exista prórroga.',
        '4. Por la existencia de riesgos legales, reputacionales o de cualquier otra índole de LAS PARTES.',
        '',
        'DÉCIMA TERCERA: CONFIDENCIALIDAD',
        'El resultado de las transacciones será mantenido bajo absoluta reserva y no podrá ser revelado en todo o en parte, por ninguna persona sin contar con la previa autorización de KUPI. No podrá ser usado en ningún caso, directa o indirectamente, en detrimento de sus intereses, ni para cualquier propósito distinto al pactado en el presente contrato, por ninguna de las partes.',
        'Lo anterior no regirá en el evento en que medie una petición de una autoridad Judicial o administrativa competente, con fines investigativos, probatorios, así mismo no será confidencial para fines de divulgación accionaria, societaria, a entes administrativos, regulatorios o estatales, que les compete conocer la misma por ejercicio de sus funciones.',
        'Toda la información que se conozca entre LAS PARTES, en desarrollo del presente contrato es confidencial y será mantenida bajo reserva hasta por el término de diez (10) años después de la terminación del contrato. LAS PARTES se obligan a proteger la información con medidas razonables de seguridad.',
        '',
        'DÉCIMA CUARTA: CLÁUSULA PENAL',
        'En caso de incumplimiento de las obligaciones de LAS PARTES, la parte incumplida pagará a favor de la otra parte, una penalidad por DOS MILLONES DE PESOS COP ($2.000.000) más IVA. Por el pago de la pena no se extingue la obligación principal, la cual podrá ser exigida separadamente. La parte que hubiera cumplido o se hubiere allanado a cumplir, podrá demandar el cumplimiento del presente contrato o la resolución de este, en ambos casos conjuntamente con el pago de la pena y la indemnización de los perjuicios pertinentes, pues la cláusula penal convenida por las partes es una sanción por el incumplimiento y no una estimación anticipada de perjuicios.',
        'La parte incumplida, renuncia expresamente a los requerimientos privados y judiciales de ley y, en caso de incumplimiento de sus obligaciones, será deudora de la cláusula penal establecida, la cual, en caso de no pagarse al momento de su exigibilidad, generará intereses moratorios conforme al Artículo 884 del Código de Comercio.',
        '',
        'DÉCIMA QUINTA: GARANTÍAS',
        'Las partes podrán acordar en cualquier momento la constitución de póliza emitida por una compañía de seguros establecida y vigilada por la Superintendencia Financiera de Colombia, con el fin de garantizar el cumplimiento del contrato.',
        '',
        'DÉCIMA SEXTA: DOCUMENTOS DEL CONTRATO',
        'Forman parte integral de este contrato los siguientes documentos: 1. Manual operativo para el uso de plataforma 3. Documentos de identificación de las partes 4. En general cualquier documento, acta o correspondencia elaborada, enviada, firmada y recibida por las partes, en relación con la ejecución del presente contrato. Todos los documentos de este contrato obligan jurídicamente y cualquier elemento que figure en ellos obligará como si se contemplara en el contrato.',
        '',
        'DÉCIMA SÉPTIMA: MÉRITO EJECUTIVO',
        'El presente documento presta mérito ejecutivo para exigirle a la parte incumplida, el cumplimiento de todas las obligaciones en él consagradas, especialmente la consagrada en la cláusula penal, por tratarse de obligaciones claras, expresas y exigibles al tenor de los arts. 422, 424 y 433 del C. G. P., las cuales no requieren de prueba diferente a la mera presentación en copia simple de este contrato debidamente suscrito por ambas partes. Ambas partes le otorgan la fuerza necesaria para presumir su autenticidad y presumir su incumplimiento con su presentación ante un juez para su respectivo cobro ejecutivo.',
        '',
        'DÉCIMA OCTAVA: ESTIPULACIONES GENERALES',
        '• Todos los impuestos, tasas y contribuciones que se generen o puedan generarse por la celebración, suscripción, ejecución, terminación o liquidación   del presente contrato incluyendo los impuestos correspondientes a cada transacción, serán asumidos y estarán a cargo de la parte que según la norma califique como sujeto pasivo del respectivo ',
        '• Controversias. Toda diferencia o controversia susceptible de transacción que surgiere entre las partes, por causa de la celebración, ejecución, interpretación, terminación o liquidación de este contrato, se someterá en primer término a procedimientos de auto composición, tales como la negociación y la conciliación. Para tal efecto, las partes involucradas en la respectiva controversia o diferencia dispondrán de treinta (30) días calendario, contados a partir de la fecha en que cualquiera de ellas requiera a la otra por escrito en tal sentido, término que podrá ser prorrogado de común acuerdo por treinta (30) días calendario adicional. Las controversias o diferencias que no pudieren resolverse en la forma antes indicada serán sometidas a la decisión de la justicia ordinaria. ',
        '• Cesión: Queda prohibido al CONTRATISTA ceder parcial o totalmente la ejecución del presente contrato a un tercero salvo previa autorización expresa y escrita del CONTRATANTE.',
        '• Ley y Jurisdicción. El presente contrato se regirá, interpretará y ejecutará de acuerdo con las leyes de la República de Colombia. ',
        '• Modificaciones. A partir de la fecha de firma del presente Contrato, cualquier modificación al mismo deberá convenirse de mutuo acuerdo entre las Partes y constar por escrito debidamente firmado por cada una de ellas. ',
        '• Aceptación del contrato. La firma, suscripción o aceptación de este contrato, podrá realizarse digitalmente. El presente contrato se entenderá aceptado cuando se envíe y/o reciba, vía correo electrónico, una copia firmada y transmitida. En este caso, el archivo PDF que se envié se considerará como un original, un documento legalmente vinculante, ejecutable y aceptado para todos los propósitos. Las partes al poner sus iniciales y firmar el presente documento reconocen que han leído y comprendido su contenido. ',
        '• Fuerza Mayor – Caso fortuito. El tratamiento que las partes darán a estos eventos será: 1. La Fuerza Mayor o el Caso Fortuito deben tener las condiciones y requisitos señalados por la ley y jurisprudencia colombiana para que sean catalogados como tales. 2. Todo evento de fuerza mayor o caso fortuito debe ser comunicado por la parte que lo invoca en un plazo máximo de 24 horas contados a partir de su ocurrencia, en caso contrario, se entenderá que no existe tal evento o circunstancia. 3. Si la notificación es recibida oportunamente, los plazos de entrega se prolongarán por un periodo equivalente al tiempo que dure la causa de fuerza mayor o caso fortuito. 4. Si la ejecución del Contrato fuere retrasada o se encontrare suspendida por más de treinta (30) días por cualquier evento de Fuerza mayor o Caso Fortuito, las Partes se reunirán para examinar de común acuerdo los términos y condiciones de la continuación de la ejecución del Contrato. Si no hubiere acuerdo entre las partes dentro de los treinta (30) días de inicio de las reuniones, cualquiera de ellas podrá notificar por escrito a la otra la rescisión del Contrato en los términos y condiciones aquí estipuladas. ',
        '• Tratamiento de datos personales. Las partes, en calidad de titulares de información, actuando libre y voluntariamente, autoriza de manera previa y expresa a la otra parte, para que directamente o a través de terceros realice el tratamiento a su información personal, tratamiento que consiste en recolectar, almacenar, usar, circular, registrar, administrar, 9 procesar, evaluar, confirmar, suprimir y actualizar la información de carácter personal que le ha suministrado, o que sobre el titular se recoja con ocasión o como consecuencia de la ejecución del contrato. Igualmente, garantizan que cualquier información personal que sea suministrada cumple con los requisitos establecidos en la Ley 1581 de 2012 y cuenta con autorización previa, consentida y susceptible de posterior consulta. Lo anterior con el fin de: 1. Desarrollar el objeto de este contrato. 2. Evaluar el desempeño contractual. 3. Remitir publicidad y publicaciones relacionadas con las actividades comerciales. 4. Facilitar el ejercicio de supervisión o interventoría a la ejecución del contrato. 5. Realizar estudios de mercado, estadísticas y encuestas. Las partes declaran que fueron informadas de manera previa a la suscripción del presente documento de lo siguiente: 1. Del tratamiento que recibirá la información personal, y la finalidad de este. 2. De la facultad de abstenerme de responder preguntas relacionadas con datos de información sensible. 3. La dirección física o electrónica de las partes y su teléfono. 4. De la finalidad del tratamiento. Los derechos que le asisten al titular de la información. 5. La información personal que será objeto de tratamiento y permanecerá en la respectiva base de datos en tanto se realice contratación. ',
        '• Control para el lavado de activos y financiación al terrorismo. Las partes certifican que: 1. Sus recursos no provienen ni se destinan al ejercicio de actividades ilícitas o de lavado de dineros provenientes de éstas o de actividades relacionadas con la financiación del terrorismo. 2. Cuentan con los medios idóneos para la prevención y control de lavado de activos y de la financiación del terrorismo y realizarán las gestiones pertinentes para efectuar las verificaciones a que haya lugar con el fin de evitar el ingreso y egreso de recursos que provengan de actividades relacionadas con lavado de activos y financiación del terrorismo. 3. Permanentemente realizan actividades encaminadas a asegurar que todos sus socios, administradores, clientes, proveedores, empleados, etc., y los recursos de estos, no se encuentren relacionados o provengan, de actividades ilícitas, particularmente de lavado de activos o financiación del terrorismo. En cumplimiento de lo anterior, las partes se obligan a: 1. Entregar información veraz y verificable para el cumplimiento de la normatividad relacionada con prevención y control de lavado de activos y de la financiación del terrorismo. 2. Actualizar sus datos suministrando la totalidad de los soportes que se requiera. En todo caso, si durante el plazo de vigencia del contrato alguna de las partes, sus administradores o socios llegaren a resultar inmiscuidos en una investigación de cualquier tipo (penal, administrativa, etc.) relacionada con actividades ilícitas, lavado de dinero o financiamiento del terrorismo, o fuesen incluidos en cualquiera de las listas de control actuales o que se creen, en forma enunciativo y no limitativa tales como las de la ONU, OFAC etc., la parte no involucrada, tendrá el derecho de terminar unilateralmente el contrato sin que por este hecho esté obligado a indemnizar ningún tipo de perjuicio. ',
        '• Anticorrupción. Las partes, mediante la suscripción del presente contrato, declaran que no ha participado, no participan y no van a participar en ninguna acción que viole las normas y leyes anticorrupción que les sea aplicables en el territorio donde las partes tengan su negocio. Las partes se obligan a no ofrecer o pagar sobornos o cualquier halago corrupto a los Colaboradores de la otra parte, ni a cualquier otro funcionario público o privado que pueda influir en la selección de su propuesta, bien sea directa o indirectamente, ni a terceras personas que por su influencia sobre funcionarios públicos, privados, colaboradores o sobre cualquier otra persona o entidad pública o privada, puedan influir sobre la asignación del contrato u órdenes. Adicionalmente las partes, podrán realizar visitas y solicitar información necesaria con el fin de evaluar el cumplimiento de las políticas y procedimientos. Sí se rehúsa a responder adecuadamente los requerimientos o aceptar la visita dará lugar a la terminación del contrato, sin indemnización alguna. Los interventores y supervisores designados o contratados por las partes están facultados para solicitar informes, aclaraciones y explicaciones sobre el desarrollo de la ejecución contractual, y serán responsables por mantener informada de los hechos o circunstancias que puedan constituir actos de corrupción tipificados como conductas punibles, o que puedan poner o pongan en riesgo el cumplimiento del contrato, o cuando tal incumplimiento se presente. Las partes 10 tendrán el derecho de terminar unilateralmente el contrato sin que por este hecho esté obligado a indemnizar ningún tipo de perjuicio, si se comprobare el incumplimiento de los compromisos anticorrupción. Adicionalmente se le aplicarán las sanciones establecidas en la Política Anticorrupción. ',
        '• Validez. El presente contrato anula todo convenio anterior y solamente podrá ser modificado por escrito suscrito por las partes.',
      ]
    },
  ];
}